### ISSUE TITLE
Question about the Attention-Based Region Proposal Network.

### ISSUE THREAD

**Issue by lixiang-ucas** [fanq15/FSOD-code#27]
Dear Qi,
     Thanks for sharing the code of your interesting work. In the design of your "Attention-Based Region Proposal Network", I'd like to know are you using the feature maps before or after ROI crop for the support images? From the pipeline figure, It seems you are using the feature map before ROI crop. But from your code (line 175 of model_builder.py), if I understand correctly, you are using the other way. In my opinion, it may be better to use the latter one, because by doing so we can avoid redundant information from the background.

**Comment by fanq15** [comment]
Yes, I use the feature map after RoI crop. This detail is not shown in the figure.

**Comment by lixiang-ucas** [comment]
got it, thanks.
