### ISSUE TITLE
A error when testing

### ISSUE THREAD

**Issue by 1179021477** [fanq15/FSOD-code#31]
magic_number = pickle_module.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 6: ordinal not in range(128)

**Comment by yushenghuo** [comment]
> magic_number = pickle_module.load(f)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 6: ordinal not in range(128)

hi, Could you plz tell how did you solve the issue, I just met the same probelm
