### ISSUE TITLE
Some advice to make your readme.md more complete

### ISSUE THREAD

**Issue by RookieHong** [fanq15/FSOD-code#41]
1. Add pandas in requirements.
2. PyYAML==3.12 according to this [issue](https://github.com/facebookresearch/DensePose/issues/37), a higher version of PyYAML causes an error when evaluation.
3. export CXXFLAGS="-std=c++11" and export CFLAGS="-std=c99" can be added to lib/make.sh to avoid some errors of compiled lib.

**Comment by fanq15** [comment]
Added. Is it ok in the [code](https://github.com/fanq15/FSOD-code/blob/fdc894d9ffabd90bf705fe7c84dfdf68d19ead47/lib/make.sh#L5)? Thank you for your advice!

**Comment by RookieHong** [comment]
It's ok now, thanks!
