### ISSUE TITLE
Found improper pictures in the FSOD dataset

### ISSUE THREAD

**Issue by fhong-jpg** [fanq15/FSOD-code#55]
The picture‘s path is fsod/images/part_1/n02925666/n02925666_15426.jpgn02925666_15426.jpg.
I was running some test on the fsod dataset and output the pictures with detection results. 
When I checked them one by one, that pic showed up and surprised me.
Fortunately no one was standing behide me then.

**Comment by fanq15** [comment]
Very sorry about that, I will process that later.

**Comment by fanq15** [comment]
Thank you for your report. I record your problem, and I will delete this issue in 1 hour to avoid to upset others. Is it on?

**Comment by fanq15** [comment]
The FSOD dataset will be cleaned again after the CVPR DDL, and other functions will be added to FewX.
